# Generated by Django 4.2.11 on 2024-03-24 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shortener',
            new_name='URL',
        ),
    ]
